// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef DRIVETRAIN_H
#define DRIVETRAIN_H
#include "Commands/Subsystem.h"
#include "./DriveTrain/DriveMotorCalculator.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class DriveTrain: public frc::Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<frc::SpeedController> rightMotor;
	std::shared_ptr<frc::SpeedController> leftMotor;
	std::shared_ptr<frc::Encoder> rightEncoderDrive;
	std::shared_ptr<frc::Encoder> leftEncoderDrive;
	std::shared_ptr<frc::Compressor> compressor;
	std::shared_ptr<frc::Solenoid> shifter;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	int goToDistanceState;
	double encoderClicksPerCentimeter;
	std::shared_ptr<DriveMotorCalculator> calculator;

public:
	DriveTrain();
	void InitDefaultCommand() override;

	void Periodic() override;
	void SetRightPower(double power);
	void SetLeftPower(double power);
	std::shared_ptr<frc::Encoder> getRightEncoder();
	std::shared_ptr<frc::Encoder> getLeftEncoder();
	bool goToDistance(double rightCentimeters, double leftCentimeters, double power);
	bool GyroTurn(double current, double turnAmount, double p, double i, double d);
	void enableCompressor();
	void shiftUp();
	void shiftDown();
	void readLeftMotor();
	double getLeftSpeed();
	double getGyroTurnError();
	double readCompressor();
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	bool highGear;
};

#endif
