// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef SCALEDETECTION_H
#define SCALEDETECTION_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

//Scale size in meters
#define SCALEMAXMAX	1.7399 //The tip of the scale plate at its max height
#define SCALEMAXMIN	1.6168 //The bottom of the scale plate at its max height
#define SCALEMINMAX	1.2534 //The tip of the scale plate at the min height
#define SCALEMINMIN	1.1303 //The top of the scale plate at the min height

#define SCALESTART	1.4351

/**
 *
 *
 * @author ExampleAuthor
 */
class ScaleDetection: public frc::Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	frc::Counter *cntFront;
	frc::Counter *cntBack;
	//frc::Counter *cntLo;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	double ReadFront();
	double ReadBack();

public:
	ScaleDetection();
	void InitDefaultCommand() override;
	void Periodic() override;
	int FoundScale();
	int GetScalePosition();
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
};

#endif
