// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef AUTONOMOUS_COMMAND_H
#define AUTONOMOUS_COMMAND_H


#include "Commands/Subsystem.h"
#include "../Robot.h"
#include "../Subsystems/Autonomous/AutoScenario.h"


/**
 *
 *
 * @author ExampleAuthor
 */


class AutonomousCommand: public frc::Command {
public:
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	AutonomousCommand();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

	void Initialize() override;
	void Execute() override;
	bool IsFinished() override;
	void End() override;
	void Interrupted() override;

private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLES


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLES

// METHODS
	void  getConsoleValues(int &autoSide, int &autoMode) const;
	void  getFmsValues(unsigned char &switchFms, unsigned char &scaleFms) const;
	void  getInputsFromDriverStation(int &auto_side, int &auto_mode, unsigned char &switch_fms, unsigned char &scale_fms);

// MEMBERS
	AutoScenarioPtrType     m_autoScenarioPtr;
};

#endif
