// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "IntakeWheelsOut.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

IntakeWheelsOut::IntakeWheelsOut(): frc::Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::intake.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void IntakeWheelsOut::Initialize() {
	done = false;
}

// Called repeatedly when this Command is scheduled to run
void IntakeWheelsOut::Execute() {
	Robot::intake->spinReverse(0.7);
	done = true;
}

// Make this return true when this Command no longer needs to run execute()
bool IntakeWheelsOut::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void IntakeWheelsOut::End() {
	Robot::intake->stopWheels();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void IntakeWheelsOut::Interrupted() {
	Robot::intake->stopWheels();
}
