// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "LowerIntake.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

LowerIntake::LowerIntake(): frc::Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::intake.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void LowerIntake::Initialize() {
	done = false;
	done2 = false;
//	Robot::intake->initMovement();

}

// Called repeatedly when this Command is scheduled to run
void LowerIntake::Execute() {
	if((Robot::manipulatorArm->currPos == 5) && (Robot::manipulatorArm->targetPos == 5))
		{
		done = true;
		return;
		}
	done2 = Robot::intake->moveTo(Robot::intake->IntakePositions::GetCube);
	if(done2)
		{
		if(Robot::manipulatorArm->currPos == 11)
			done = Robot::manipulatorArm->moveTo(5);
		else
			done = true;
		}
}

// Make this return true when this Command no longer needs to run execute()
bool LowerIntake::IsFinished() {
    return done;
}

// Called once after isFinished returns true
void LowerIntake::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void LowerIntake::Interrupted() {

}
