// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
#include "ctre/Phoenix.h"
#include "CANTalon.h"
#include "WPILib.h"

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<frc::SpeedController> RobotMap::driveTrainLeftMotor;
std::shared_ptr<frc::SpeedController> RobotMap::driveTrainRightMotor;
std::shared_ptr<frc::Encoder> RobotMap::driveTrainrightEncoder;
std::shared_ptr<frc::Encoder> RobotMap::driveTrainleftEncoder;
std::shared_ptr<frc::DigitalInput> RobotMap::smallLidarsDist1;


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<TalonSRX> RobotMap::manipulatorArmShoulder;
std::shared_ptr<TalonSRX> RobotMap::manipulatorArmElbow;
std::shared_ptr<TalonSRX> RobotMap::manipulatorArmWrist;

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    frc::LiveWindow *lw = frc::LiveWindow::GetInstance();

    driveTrainLeftMotor.reset(new frc::VictorSP(0));
    lw->AddActuator("DriveTrain", "LeftMotor", std::static_pointer_cast<frc::VictorSP>(driveTrainLeftMotor));
    
    driveTrainRightMotor.reset(new frc::VictorSP(1));
    lw->AddActuator("DriveTrain", "RightMotor", std::static_pointer_cast<frc::VictorSP>(driveTrainRightMotor));
    
    driveTrainrightEncoder.reset(new frc::Encoder(0, 1, false, frc::Encoder::k4X));
    lw->AddSensor("DriveTrain", "rightEncoder", driveTrainrightEncoder);
    driveTrainrightEncoder->SetDistancePerPulse(1.0);
    driveTrainrightEncoder->SetPIDSourceType(frc::PIDSourceType::kRate);
    driveTrainleftEncoder.reset(new frc::Encoder(2, 3, false, frc::Encoder::k4X));
    lw->AddSensor("DriveTrain", "leftEncoder", driveTrainleftEncoder);
    driveTrainleftEncoder->SetDistancePerPulse(1.0);
    driveTrainleftEncoder->SetPIDSourceType(frc::PIDSourceType::kRate);
    smallLidarsDist1.reset(new frc::DigitalInput(9));
    lw->AddSensor("SmallLidars", "Dist1", smallLidarsDist1);
    
    manipulatorArmShoulder.reset(new CANTalon(0));
    lw->AddActuator("ManipulatorArm", "Shoulder", manipulatorArmShoulder);
    
    manipulatorArmElbow.reset(new CANTalon(1));
    lw->AddActuator("ManipulatorArm", "Elbow", manipulatorArmElbow);
    
    manipulatorArmWrist.reset(new CANTalon(2));
    lw->AddActuator("ManipulatorArm", "Wrist", manipulatorArmWrist);
    


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
