// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ROBOTMAP_H
#define ROBOTMAP_H

#define FLIGHTBOT	0

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "WPILib.h"
#include "ctre/Phoenix.h"

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static std::shared_ptr<frc::SpeedController> driveTrainrightMotor;
	static std::shared_ptr<frc::SpeedController> driveTrainleftMotor;
	static std::shared_ptr<frc::Encoder> driveTrainrightEncoderDrive;
	static std::shared_ptr<frc::Encoder> driveTrainleftEncoderDrive;
	static std::shared_ptr<frc::Compressor> driveTrainCompressor;
	static std::shared_ptr<frc::Solenoid> driveTrainshifter;
	static std::shared_ptr<WPI_TalonSRX> manipulatorArmshoulder;
	static std::shared_ptr<WPI_TalonSRX> manipulatorArmelbow;
	static std::shared_ptr<WPI_TalonSRX> manipulatorArmwrist;
	static std::shared_ptr<WPI_VictorSPX> manipulatorArmshoulderSlave;
	static std::shared_ptr<WPI_VictorSPX> manipulatorArmelbowSlave;
	static std::shared_ptr<frc::DoubleSolenoid> manipulatorArmclaw;
	static std::shared_ptr<frc::Relay> manipulatorArmindicator;
	static std::shared_ptr<frc::DigitalInput> manipulatorArmcubeDetector;
	static std::shared_ptr<frc::DoubleSolenoid> manipulatorArmshoulderClimber;
	static std::shared_ptr<WPI_TalonSRX> intakelifter;
	static std::shared_ptr<frc::SpeedController> intakerightWheels;
	static std::shared_ptr<frc::SpeedController> intakeleftWheels;
	static std::shared_ptr<frc::Solenoid> intakereleaser;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	static void init();
};
#endif
